version: 1.0.{build}

platform:
    - MSVC_2015_x86
    - MSVC_2015_x64
    - MSVC_2017_x86
    - MSVC_2017_x64

image:
    - Visual Studio 2015
    - Visual Studio 2017

install:
    - scripts\ci-pre.cmd

build_script:
    - scripts\ci-build.cmd

test_script:
    - scripts\ci-test.cmd
