version: 1.0.{build}
image: Visual Studio 2015
platform: 
    - MSVC_2015_X86
    - MSVC_2015_X64
    # - MSVC_2017_x86
    # - MSVC_2017_x64
install:
    - scripts\ci-pre.cmd
build_script:
    - scripts\ci-build.cmd
test_script:
    - scripts\ci-test.cmd
